import ISorter from "../ISorter";

/**
 * BubbleSorter implements the ISorter interface using
 * the inefficient bubble-sort algorithm.
 *
 * Do not edit this file.
 */
export default class BubbleSorter<E> implements ISorter<E> {

    constructor() {
    }

    public sort(list: E[], compareFun: (e1: E, e2: E) => number): void {
        let n = list.length;
        for (let i = 0; i < n - 1; i++) {
            for (let j = 0; j < n - i - 1; j++) {
                if (compareFun(list[j], list[j + 1]) > 0) {
                    let temp = list[j];
                    list[j] = list[j + 1];
                    list[j + 1] = temp;
                }
            }
        }
    }
}