/**
 * An ISorter is an algorithm for sorting an array.
 *
 * Do not edit this file.
 */
export default interface ISorter<E> {
  /**
   * @param list a list to be sorted (in place: the sort function sorts the list by adjusting the order of elements directly in that list)
   * @param compareFunction is a function that takes two arguments, x and y. It returns a negative value if x < y, it returns 0 if x =y, and it returns a positive value otherwise.
   */
  sort(list: E[], compareFunction: (x: E, y: E) => number) : void
}