import ISorter from "./ISorter";
import BubbleSorter from "./provided/BubbleSorter";
import Sorter1 from "./task2/Sorter1";
import Sorter2 from "./task2/Sorter2";
/*
 * Do not edit this file.
 */
export default class SorterFactory<E> {
    private implementation: string;

    constructor(implementation?: string) {
        this.implementation = implementation;
    }

    createSorter(): ISorter<E> {
        switch (this.implementation) {
            case "Sorter1":
                return new Sorter1<E>();
            case "Sorter2":
                return new Sorter2<E>();
            case "BubbleSorter":
            default:
                return new BubbleSorter<E>();
        }
    }
}