  
name: "CI"

on: workflow_dispatch

jobs:
  Release-deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:   
          node-version: '14'
